version: "3"

services:
  api:
    build: ./qrapi/
    container_name: eyetech.qrapi
    networks:
      - backend
    ports:
      - "5000:5000"
    volumes:
      - ./qrapi:/app
  frontend:
    container_name: eyetech.qrfront
    build: ./qrfront/
    networks:
      - backend
    ports:
      - 80:8080
    depends_on:
      - api
    volumes:
      - /qrfront:/app
networks:
  backend:
    driver: bridge